### ISSUE TITLE
Identity?

### ISSUE THREAD

**Issue by ploum** [PigeonProtocolConsortium/pigeon-spec#3]
Hello,

Is there any notion of identity beside a  ED25519 key?

Is there anything preventing pigeon protocol to work with OpenPGP, piggybacking on the PGP web of trust?

**Comment by RickCarlino** [comment]
Hey @ploum -

First off- thanks for taking an interest in the project!

To answer your question, the current protocol considers an identity and an ED25519 keypair to be the same thing. The protocol does not associate any additional information to the identity beyond that. This is similar to Secure Scuttlebutt, which is the main inspiration for the protocol (an explanation about how SSB handles identity can be found [here](https://handbook.scuttlebutt.nz/concepts/identity)). Any extra data that you wish to associate with an identity must be handled at the application layer rather than the protocol layer. As an example, in Secure Scuttlebutt, if you wish to assign a human-readable name to an identity you or one of your peers would need to append a message to your feed that assigns the name to a keypair. Your application would then parse and assign that name to the user's profile. I would expect Pigeon applications to behave similarly.

Does that help answer your question? Apologies ahead of time if I am misunderstanding the question, I do not use PGP web of trust personally so I am not 100% familiar with its specifics.

**Comment by ploum** [comment]
Thanks for the fast reply.  I’m currently thinking about doing a similar protocol, albeit simpler and based on Gemini (see gemini://rawtext.club/~ploum/2021-10-25-offmini2.gmi ).

But before reinventing the wheel, I’m really trying to understand what you did to know if it would be better to use yours or, if not, to clearly identify the differences.

**Comment by RickCarlino** [comment]
@ploum This is a great read and I support the idea 100%- it's nice to see that other folks are drawing the same conclusions about hyper-connectivity and the benefits of offline-only.

**RE: Identity.** I have a better understanding of your question now. To answer it more succinctly, Pigeon is a send-receive type network and the identity model is exactly the same as bitcoin wallets. 
**RE: $UNFULLFILLED** I was considering a similar approach, though I don't think I've published anything about it publicly yet. I was planning on adding a "have/want" protocol for advertising blobs.
**RE: NNCP** I had no idea about this one! Thanks for bringing it to my attention. I hope to take a deeper look over the weekend. It looks like a new version was published just today. Wow!
**With regards to de-duplication** Does your idea use content addressing at all?
**RE: Web of Trust content filtering** If I am understanding the idea correctly, the protocol will only supply data from known nodes and uses this as an anti-abuse mechanism. Pigeon differs slightly here because it has (or aspires to have) a concept of "listening distance" which was modeled after SSB. Although it is not perfect and you do occasionally find yourself blocking SSB users, it allows for the discovery of new content and new peers in an offline context. I would very much like the protocol to support content discovery, albeit at a slower pace than what an online network would allow.

Anyway, this is all very exciting stuff and I am very happy to see that other developers are interested in exploring the concept of "off-grid networking". The only reason I paused development on Pigeon was that I don't like working in a vacuum. I hope to hear more about your project and see where it goes or if there is room for collaboration. My contact info is pretty easy to find and I would love to keep this discussion going if you want to talk about it more.

**Comment by ploum** [comment]
Hi Rick,

Unfortunately, I didn’t find your email address. Just to say that, currently, I’ve not much to share than what I put on my gemlog. I’m investigating more deeply opengpg and, as soon as I’ve some questions or things to share, I would be happy to discuss them by email. I clearly feel that a kind of decentralized offline gemini is needed, something as simple as possible even if it implies really reducing usecases. I don’t know if you are aligned with that and if pigeon is "simple enough" for what I envision.

You can contact me :  lionel on  ploum dot net.

**Comment by RickCarlino** [comment]
@ploum Sending you an email now. It looks like I already had you in my contact list from a discussion we had back in February.

I am glad that, like me, you see the need for a truly offline-only data transfer system. I would be open to doing a hard-fork v2 re-write, possibly changing the project's name along the way to avoid legacy baggage. I spent about 1 year working on Pigeon and in doing so, I learned a lot of hard lessons that could shape a second edition of the protocol. Pigeon is certainly a protocol with few moving parts (and a v2 of the project might even have less).

Let's keep in touch and see where this goes.
